[package]
name = "fugue-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8",  features = ["macros", "multipart"]} 
axum-extra = { version = "0.12.2", features = ["cookie"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net"] }
dotenvy = "0.15"
serde = { version = "1.0", features = ["derive",] }
chrono = { version = "0.4.42", features = ["serde"] }
jsonwebtoken = { version = "10", features = ["rust_crypto"] }
bcrypt = "0.17.1"
cookie = "0.18"
time = "0.3"
ts-rs = "11.1.0"

tower = "0.5.2"
tower-http = "0.6.6"

sea-orm = { version = "1.0", features = ["runtime-tokio-native-tls", "sqlx-postgres", "macros"] }
sea-orm-migration = { version = "1", features = ["sqlx-mysql", "runtime-async-std-native-tls"] }

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
tracing-error = "0.2"
serde_json = "1.0.145"

aws-config = "1.8.12"
aws-sdk-s3 = "1.119.0"
tempfile = "3.24.0"
uuid = { version = "1.19.0", features = ["v4"] }
